apiVersion: v1
appVersion: 1.5.0
description: Collect metrics with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/main/helm-chart/charts/splunk-kubernetes-metrics
keywords:
- splunk
- monitoring
- metric
maintainers:
- email: DataEdge@splunk.com
  name: Splunk Inc.
name: splunk-kubernetes-metrics
sources:
- https://github.com/splunk/splunk-connect-for-kubernetes/tree/main/helm-chart/charts/splunk-kubernetes-metrics
- https://github.com/splunk/fluent-plugin-splunk-hec
- https://github.com/splunk/fluent-plugin-kubernetes-metrics
- https://github.com/splunk/fluent-plugin-k8s-metrics-agg
version: 1.5.0
